version: '3'
services:
  mongo:
    image: mongo
    container_name: 'NCNewsMongo'
    restart: always
    volumes:
      - mongo:/var/lib/mongo
    networks:
      - northcoders-news

  ncnews-be:
    container_name: 'NCNewsAPI'
    build:
      context: ./NCNews-BE
    command: /bin/sh -c 'yarn && node seed/seed.js && yarn start'
    volumes:
      - ./:/app:delegated
      - node_modules:/app/node_modules
    ports:
      - '8000:8000'
    networks:
      - northcoders-news

  ncnews-fe:
    container_name: 'NCNewsClient'
    build:
      context: ./NCNews-FE
    command: /bin/sh -c 'yarn && yarn build && yarn start'
    volumes:
      - ./:/app:delegated
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    networks:
      - northcoders-news

volumes:
  mongo:
  node_modules:

networks:
  northcoders-news:
    external:
      name: northcoders-news
